name: barcode_scan2
description: A flutter plugin for scanning 2D barcodes and QRCodes via camera.
version: 4.7.2
homepage: https://github.com/mono0926/barcode_scan2

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^6.0.0

dev_dependencies:
  pedantic_mono: ^1.35.0

environment:
  sdk: ^3.5.0
  flutter: '>=3.13.0'

flutter:
  plugin:
    platforms:
      android:
        package: de.mintware.barcode_scan
        pluginClass: BarcodeScanPlugin
      ios:
        pluginClass: BarcodeScanPlugin
